# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LiBei
email: libei.ly@alibaba-inc.com
description: > # this means to ignore newlines until "baseurl:"
  前端工程师
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  libeiLy
github_url: "https://github.com/libeily"

# Build settings
markdown: kramdown
paginate: 2
paginate_path: "blog/page:num"
gems: [jekyll-paginate]